/*

 BIRB-SPRITE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char birb[] =
{
  0x00,0x00,0x06,0x06,0xFB,0xF9,0x8E,0xF6,
  0x68,0x58,0xF0,0xF0,0x80,0x80,0x00,0x00,
  0xE0,0xE0,0xB6,0xF6,0xDB,0xB9,0x4E,0x76,
  0x78,0x48,0xF0,0xF0,0x80,0x80,0x00,0x00
};

/* End of BIRB-SPRITE.C */
